# Generated by Django 4.1.7 on 2023-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_count',
            field=models.IntegerField(default=1),
        ),
    ]
